export interface StarterTemplate {
  id: string;
  name: string;
  description: string;
  category: "real_estate" | "retail" | "event" | "roofing" | "auto";
  previewImage: string;
  size: "4x6" | "6x9" | "6x11" | "letter" | "trifold";
  industryVertical: "roofing" | "rei" | "auto_service" | "auto_warranty" | "auto_buyback";
  layers: any;
}

export const starterTemplates: StarterTemplate[] = [
  {
    id: "rei-postcard-1",
    name: "Real Estate Investment Postcard",
    description: "Professional postcard for cash home buyers",
    category: "real_estate",
    previewImage: "🏠",
    size: "6x9",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#1a365d",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 80,
          width: 800,
          height: 100,
          text: "We Buy Houses Fast For Cash",
          fontSize: 48,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 50,
          y: 200,
          width: 800,
          height: 60,
          text: "Any Condition • Any Situation • Fair Offers",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#f7fafc",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 300,
          y: 400,
          width: 300,
          height: 80,
          fill: "#e53e3e",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 300,
          y: 420,
          width: 300,
          height: 40,
          text: "Call Now: {{phone}}",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "retail-promo-1",
    name: "Retail Sale Promotion",
    description: "Eye-catching promotional postcard for retail sales",
    category: "retail",
    previewImage: "🛍️",
    size: "6x11",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 1100, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 1100,
          height: 600,
          fill: "#fef3c7",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "accent-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 1100,
          height: 150,
          fill: "#dc2626",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Header Accent",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 40,
          width: 1000,
          height: 80,
          text: "HUGE SALE EVENT",
          fontSize: 64,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "discount-1",
          type: "text",
          x: 200,
          y: 220,
          width: 700,
          height: 120,
          text: "50% OFF",
          fontSize: 96,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#dc2626",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Discount",
        },
        {
          id: "details-1",
          type: "text",
          x: 200,
          y: 380,
          width: 700,
          height: 60,
          text: "Visit us at {{address}} or shop online",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#1f2937",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Details",
        },
        {
          id: "expires-1",
          type: "text",
          x: 200,
          y: 480,
          width: 700,
          height: 40,
          text: "Offer expires {{expiry_date}}",
          fontSize: 20,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#6b7280",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Expiry",
        },
      ],
    },
  },
  {
    id: "event-invite-1",
    name: "Event Invitation",
    description: "Elegant invitation for special events",
    category: "event",
    previewImage: "🎉",
    size: "4x6",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 400 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 400,
          fill: "#f9fafb",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "border-1",
          type: "rect",
          x: 20,
          y: 20,
          width: 560,
          height: 360,
          fill: "transparent",
          stroke: "#6366f1",
          strokeWidth: 4,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Border",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 60,
          width: 500,
          height: 50,
          text: "You're Invited!",
          fontSize: 42,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#6366f1",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "event-name-1",
          type: "text",
          x: 50,
          y: 140,
          width: 500,
          height: 60,
          text: "{{event_name}}",
          fontSize: 32,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#1f2937",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Event Name",
        },
        {
          id: "date-1",
          type: "text",
          x: 50,
          y: 220,
          width: 500,
          height: 40,
          text: "{{event_date}} at {{event_time}}",
          fontSize: 22,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#4b5563",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Date & Time",
        },
        {
          id: "location-1",
          type: "text",
          x: 50,
          y: 280,
          width: 500,
          height: 40,
          text: "{{venue_name}}",
          fontSize: 20,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#6b7280",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Location",
        },
      ],
    },
  },
  {
    id: "roofing-promo-1",
    name: "Roofing Services Postcard",
    description: "Professional postcard for roofing contractors",
    category: "roofing",
    previewImage: "🏗️",
    size: "6x9",
    industryVertical: "roofing",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#0f172a",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "accent-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 120,
          fill: "#f97316",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Header Accent",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 30,
          width: 800,
          height: 70,
          text: "Expert Roofing Services",
          fontSize: 52,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 50,
          y: 180,
          width: 800,
          height: 80,
          text: "Free Inspection & Estimate",
          fontSize: 36,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#f97316",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Offer",
        },
        {
          id: "features-1",
          type: "text",
          x: 50,
          y: 300,
          width: 800,
          height: 120,
          text: "✓ Licensed & Insured\n✓ 25+ Years Experience\n✓ Lifetime Warranty",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#e2e8f0",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Features",
        },
        {
          id: "cta-1",
          type: "text",
          x: 50,
          y: 480,
          width: 800,
          height: 60,
          text: "Call Today: {{phone}}",
          fontSize: 32,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA",
        },
      ],
    },
  },
  {
    id: "auto-service-1",
    name: "Auto Service Special",
    description: "Promotional postcard for auto service centers",
    category: "auto",
    previewImage: "🚗",
    size: "6x9",
    industryVertical: "auto_service",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#ffffff",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "accent-top-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 20,
          fill: "#2563eb",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Top Accent",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 80,
          width: 800,
          height: 80,
          text: "Special Service Offer",
          fontSize: 56,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#1e3a8a",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "offer-1",
          type: "rect",
          x: 150,
          y: 220,
          width: 600,
          height: 140,
          fill: "#dbeafe",
          stroke: "#2563eb",
          strokeWidth: 3,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Offer Box",
        },
        {
          id: "offer-text-1",
          type: "text",
          x: 170,
          y: 250,
          width: 560,
          height: 80,
          text: "$29.99 Oil Change\n+ Free Multi-Point Inspection",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#1e3a8a",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Offer Details",
        },
        {
          id: "footer-1",
          type: "text",
          x: 50,
          y: 450,
          width: 800,
          height: 100,
          text: "{{business_name}}\n{{phone}} • {{address}}",
          fontSize: 22,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#374151",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Contact Info",
        },
      ],
    },
  },
];

export const getTemplatesByCategory = (category: StarterTemplate["category"]) => {
  return starterTemplates.filter((template) => template.category === category);
};

export const getTemplateById = (id: string) => {
  return starterTemplates.find((template) => template.id === id);
};
