import reiPostcardPreview from "@/assets/template-previews/rei-postcard.jpg";
import retailPromoPreview from "@/assets/template-previews/retail-promo.jpg";
import eventInvitePreview from "@/assets/template-previews/event-invite.jpg";
import roofingServicesPreview from "@/assets/template-previews/roofing-services.jpg";
import autoServicePreview from "@/assets/template-previews/auto-service.jpg";
import healthcareCheckupPreview from "@/assets/template-previews/healthcare-checkup.jpg";
import legalServicesPreview from "@/assets/template-previews/legal-services.jpg";
import realtorListingPreview from "@/assets/template-previews/realtor-listing.jpg";
import homeServicesPreview from "@/assets/template-previews/home-services.jpg";
import fitnessGymPreview from "@/assets/template-previews/fitness-gym.jpg";
import restaurantPromoPreview from "@/assets/template-previews/restaurant-promo.jpg";
import financialAdvisorPreview from "@/assets/template-previews/financial-advisor.jpg";
import landscapingPreview from "@/assets/template-previews/landscaping.jpg";
import veterinaryPreview from "@/assets/template-previews/veterinary.jpg";
import insurancePreview from "@/assets/template-previews/insurance.jpg";
import dentalPreview from "@/assets/template-previews/dental.jpg";
import movingCompanyPreview from "@/assets/template-previews/moving-company.jpg";

export interface StarterTemplate {
  id: string;
  name: string;
  description: string;
  category: "real_estate" | "retail" | "event" | "roofing" | "auto" | "healthcare" | "legal" | "home_services" | "fitness" | "restaurant" | "financial" | "landscaping" | "veterinary" | "insurance" | "dental" | "moving";
  previewImage: string;
  thumbnailUrl: string;
  size: "4x6" | "6x9" | "6x11" | "letter" | "trifold";
  industryVertical: "roofing" | "rei" | "auto_service" | "auto_warranty" | "auto_buyback";
  layers: any;
}

export const starterTemplates: StarterTemplate[] = [
  {
    id: "rei-postcard-1",
    name: "Real Estate Investment Postcard",
    description: "Professional postcard for cash home buyers",
    category: "real_estate",
    previewImage: "🏠",
    thumbnailUrl: reiPostcardPreview,
    size: "6x9",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#1a365d",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 80,
          width: 800,
          height: 100,
          text: "We Buy Houses Fast For Cash",
          fontSize: 48,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 50,
          y: 200,
          width: 800,
          height: 60,
          text: "Any Condition • Any Situation • Fair Offers",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#f7fafc",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 300,
          y: 400,
          width: 300,
          height: 80,
          fill: "#e53e3e",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 300,
          y: 420,
          width: 300,
          height: 40,
          text: "Call Now: {{phone}}",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "retail-promo-1",
    name: "Retail Sale Promotion",
    description: "Eye-catching promotional postcard for retail sales",
    category: "retail",
    previewImage: "🛍️",
    thumbnailUrl: retailPromoPreview,
    size: "6x11",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 1100, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 1100,
          height: 600,
          fill: "#fef3c7",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "accent-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 1100,
          height: 150,
          fill: "#dc2626",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Header Accent",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 40,
          width: 1000,
          height: 80,
          text: "HUGE SALE EVENT",
          fontSize: 64,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "discount-1",
          type: "text",
          x: 200,
          y: 220,
          width: 700,
          height: 120,
          text: "50% OFF",
          fontSize: 96,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#dc2626",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Discount",
        },
        {
          id: "details-1",
          type: "text",
          x: 200,
          y: 380,
          width: 700,
          height: 60,
          text: "Visit us at {{address}} or shop online",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#1f2937",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Details",
        },
        {
          id: "expires-1",
          type: "text",
          x: 200,
          y: 480,
          width: 700,
          height: 40,
          text: "Offer expires {{expiry_date}}",
          fontSize: 20,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#6b7280",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Expiry",
        },
      ],
    },
  },
  {
    id: "event-invite-1",
    name: "Event Invitation",
    description: "Elegant invitation for special events",
    category: "event",
    previewImage: "🎉",
    thumbnailUrl: eventInvitePreview,
    size: "4x6",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 400 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 400,
          fill: "#f9fafb",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "border-1",
          type: "rect",
          x: 20,
          y: 20,
          width: 560,
          height: 360,
          fill: "transparent",
          stroke: "#6366f1",
          strokeWidth: 4,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Border",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 60,
          width: 500,
          height: 50,
          text: "You're Invited!",
          fontSize: 42,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#6366f1",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "event-name-1",
          type: "text",
          x: 50,
          y: 140,
          width: 500,
          height: 60,
          text: "{{event_name}}",
          fontSize: 32,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#1f2937",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Event Name",
        },
        {
          id: "date-1",
          type: "text",
          x: 50,
          y: 220,
          width: 500,
          height: 40,
          text: "{{event_date}} at {{event_time}}",
          fontSize: 22,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#4b5563",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Date & Time",
        },
        {
          id: "location-1",
          type: "text",
          x: 50,
          y: 280,
          width: 500,
          height: 40,
          text: "{{venue_name}}",
          fontSize: 20,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#6b7280",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Location",
        },
      ],
    },
  },
  {
    id: "roofing-promo-1",
    name: "Roofing Services Postcard",
    description: "Professional postcard for roofing contractors",
    category: "roofing",
    previewImage: "🏗️",
    thumbnailUrl: roofingServicesPreview,
    size: "6x9",
    industryVertical: "roofing",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#0f172a",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "accent-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 120,
          fill: "#f97316",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Header Accent",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 30,
          width: 800,
          height: 70,
          text: "Expert Roofing Services",
          fontSize: 52,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 50,
          y: 180,
          width: 800,
          height: 80,
          text: "Free Inspection & Estimate",
          fontSize: 36,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#f97316",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Offer",
        },
        {
          id: "features-1",
          type: "text",
          x: 50,
          y: 300,
          width: 800,
          height: 120,
          text: "✓ Licensed & Insured\n✓ 25+ Years Experience\n✓ Lifetime Warranty",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#e2e8f0",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Features",
        },
        {
          id: "cta-1",
          type: "text",
          x: 50,
          y: 480,
          width: 800,
          height: 60,
          text: "Call Today: {{phone}}",
          fontSize: 32,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA",
        },
      ],
    },
  },
  {
    id: "auto-service-1",
    name: "Auto Service Special",
    description: "Promotional postcard for auto service centers",
    category: "auto",
    previewImage: "🚗",
    thumbnailUrl: autoServicePreview,
    size: "6x9",
    industryVertical: "auto_service",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#ffffff",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "accent-top-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 20,
          fill: "#2563eb",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Top Accent",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 80,
          width: 800,
          height: 80,
          text: "Special Service Offer",
          fontSize: 56,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#1e3a8a",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "offer-1",
          type: "rect",
          x: 150,
          y: 220,
          width: 600,
          height: 140,
          fill: "#dbeafe",
          stroke: "#2563eb",
          strokeWidth: 3,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Offer Box",
        },
        {
          id: "offer-text-1",
          type: "text",
          x: 170,
          y: 250,
          width: 560,
          height: 80,
          text: "$29.99 Oil Change\n+ Free Multi-Point Inspection",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#1e3a8a",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Offer Details",
        },
        {
          id: "footer-1",
          type: "text",
          x: 50,
          y: 450,
          width: 800,
          height: 100,
          text: "{{business_name}}\n{{phone}} • {{address}}",
          fontSize: 22,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#374151",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Contact Info",
        },
      ],
    },
  },
  {
    id: "healthcare-checkup-1",
    name: "Healthcare Checkup Reminder",
    description: "Professional medical appointment reminder postcard",
    category: "healthcare",
    previewImage: "🏥",
    thumbnailUrl: healthcareCheckupPreview,
    size: "6x9",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#f0f9ff",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 80,
          width: 800,
          height: 80,
          text: "Schedule Your Annual Checkup",
          fontSize: 44,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#0369a1",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "body-1",
          type: "text",
          x: 100,
          y: 220,
          width: 700,
          height: 150,
          text: "Regular checkups help maintain your health and prevent future issues.\n\nCall us today to schedule your appointment.",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#1e40af",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Body Text",
        },
        {
          id: "cta-1",
          type: "text",
          x: 50,
          y: 460,
          width: 800,
          height: 60,
          text: "Call: {{phone}} • Visit: {{website}}",
          fontSize: 26,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#0369a1",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA",
        },
      ],
    },
  },
  {
    id: "legal-services-1",
    name: "Legal Services Firm",
    description: "Sophisticated law firm services postcard",
    category: "legal",
    previewImage: "⚖️",
    thumbnailUrl: legalServicesPreview,
    size: "6x9",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#1e3a5f",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 100,
          width: 800,
          height: 100,
          text: "Expert Legal Representation",
          fontSize: 48,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#d4af37",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "services-1",
          type: "text",
          x: 100,
          y: 260,
          width: 700,
          height: 150,
          text: "• Personal Injury\n• Business Law\n• Estate Planning\n• Family Law",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Services",
        },
        {
          id: "cta-1",
          type: "text",
          x: 50,
          y: 480,
          width: 800,
          height: 50,
          text: "Free Consultation: {{phone}}",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#d4af37",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA",
        },
      ],
    },
  },
  {
    id: "realtor-listing-1",
    name: "Realtor Property Listing",
    description: "Elegant real estate agent property showcase",
    category: "real_estate",
    previewImage: "🏡",
    thumbnailUrl: realtorListingPreview,
    size: "6x9",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#ffffff",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 60,
          width: 800,
          height: 70,
          text: "Your Dream Home Awaits",
          fontSize: 44,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#b8860b",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "agent-1",
          type: "text",
          x: 50,
          y: 180,
          width: 800,
          height: 200,
          text: "{{full_name}}\nProfessional Real Estate Agent\n\nSpecializing in luxury properties and first-time buyers",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#374151",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Agent Info",
        },
        {
          id: "cta-1",
          type: "text",
          x: 50,
          y: 460,
          width: 800,
          height: 70,
          text: "Call {{phone}} • {{email}}",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#b8860b",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Contact",
        },
      ],
    },
  },
  {
    id: "home-services-1",
    name: "Home Services HVAC",
    description: "Professional HVAC and plumbing services postcard",
    category: "home_services",
    previewImage: "🔧",
    thumbnailUrl: homeServicesPreview,
    size: "6x9",
    industryVertical: "auto_service",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#0c4a6e",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 80,
          width: 800,
          height: 90,
          text: "24/7 Emergency Service",
          fontSize: 52,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#f97316",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "services-1",
          type: "text",
          x: 100,
          y: 240,
          width: 700,
          height: 180,
          text: "✓ HVAC Repair & Installation\n✓ Plumbing Services\n✓ Water Heaters\n✓ Emergency Repairs",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Services",
        },
        {
          id: "cta-1",
          type: "text",
          x: 50,
          y: 480,
          width: 800,
          height: 60,
          text: "Call Now: {{phone}}",
          fontSize: 34,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#f97316",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA",
        },
      ],
    },
  },
  {
    id: "fitness-gym-1",
    name: "Fitness Gym Membership",
    description: "Energetic gym membership promotional postcard",
    category: "fitness",
    previewImage: "💪",
    thumbnailUrl: fitnessGymPreview,
    size: "6x9",
    industryVertical: "auto_service",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#1f2937",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 100,
          width: 800,
          height: 100,
          text: "GET FIT TODAY",
          fontSize: 64,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ef4444",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "offer-1",
          type: "text",
          x: 100,
          y: 260,
          width: 700,
          height: 120,
          text: "Join Now & Get\n50% Off First Month",
          fontSize: 36,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Offer",
        },
        {
          id: "cta-1",
          type: "text",
          x: 50,
          y: 450,
          width: 800,
          height: 80,
          text: "Visit {{website}} • Call {{phone}}",
          fontSize: 26,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ef4444",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA",
        },
      ],
    },
  },
  {
    id: "restaurant-promo-1",
    name: "Restaurant Grand Opening",
    description: "Appetizing restaurant promotion postcard",
    category: "restaurant",
    previewImage: "🍽️",
    thumbnailUrl: restaurantPromoPreview,
    size: "6x9",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#431407",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 80,
          width: 800,
          height: 100,
          text: "Grand Opening Special",
          fontSize: 56,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#fbbf24",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "offer-1",
          type: "text",
          x: 100,
          y: 240,
          width: 700,
          height: 120,
          text: "20% Off Your First Visit\nComplimentary Appetizer",
          fontSize: 32,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Offer",
        },
        {
          id: "details-1",
          type: "text",
          x: 50,
          y: 420,
          width: 800,
          height: 100,
          text: "{{restaurant_name}}\n{{address}} • {{phone}}",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#fbbf24",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Details",
        },
      ],
    },
  },
  {
    id: "financial-advisor-1",
    name: "Financial Planning Services",
    description: "Professional financial advisor marketing postcard",
    category: "financial",
    previewImage: "💰",
    thumbnailUrl: financialAdvisorPreview,
    size: "6x9",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#059669",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 100,
          width: 800,
          height: 100,
          text: "Plan Your Financial Future",
          fontSize: 48,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "services-1",
          type: "text",
          x: 100,
          y: 260,
          width: 700,
          height: 140,
          text: "• Retirement Planning\n• Investment Management\n• Tax Strategy\n• Estate Planning",
          fontSize: 26,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#f0fdfa",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Services",
        },
        {
          id: "cta-1",
          type: "text",
          x: 50,
          y: 470,
          width: 800,
          height: 60,
          text: "Free Consultation: {{phone}}",
          fontSize: 30,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA",
        },
      ],
    },
  },
  {
    id: "landscaping-1",
    name: "Landscaping Services",
    description: "Beautiful lawn care and landscaping postcard",
    category: "landscaping",
    previewImage: "🌱",
    thumbnailUrl: landscapingPreview,
    size: "6x9",
    industryVertical: "auto_service",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#16a34a",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 90,
          width: 800,
          height: 90,
          text: "Transform Your Yard",
          fontSize: 54,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "services-1",
          type: "text",
          x: 100,
          y: 250,
          width: 700,
          height: 160,
          text: "✓ Lawn Maintenance\n✓ Garden Design\n✓ Tree & Shrub Care\n✓ Seasonal Cleanup",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#f0fdf4",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Services",
        },
        {
          id: "cta-1",
          type: "text",
          x: 50,
          y: 470,
          width: 800,
          height: 70,
          text: "Free Estimate: {{phone}}",
          fontSize: 34,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA",
        },
      ],
    },
  },
  {
    id: "veterinary-1",
    name: "Veterinary Pet Care",
    description: "Friendly veterinary clinic postcard",
    category: "veterinary",
    previewImage: "🐾",
    thumbnailUrl: veterinaryPreview,
    size: "6x9",
    industryVertical: "auto_service",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#fef3c7",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 80,
          width: 800,
          height: 80,
          text: "Caring for Your Pets",
          fontSize: 50,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#b45309",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "services-1",
          type: "text",
          x: 100,
          y: 230,
          width: 700,
          height: 180,
          text: "Comprehensive Veterinary Care\n• Wellness Exams\n• Vaccinations\n• Surgery & Dental\n• Emergency Services",
          fontSize: 26,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#78350f",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Services",
        },
        {
          id: "cta-1",
          type: "text",
          x: 50,
          y: 470,
          width: 800,
          height: 60,
          text: "Schedule Appointment: {{phone}}",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#b45309",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA",
        },
      ],
    },
  },
  {
    id: "insurance-1",
    name: "Insurance Agency",
    description: "Trustworthy insurance services postcard",
    category: "insurance",
    previewImage: "🛡️",
    thumbnailUrl: insurancePreview,
    size: "6x9",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#0ea5e9",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 90,
          width: 800,
          height: 100,
          text: "Protect What Matters Most",
          fontSize: 46,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "types-1",
          type: "text",
          x: 100,
          y: 250,
          width: 700,
          height: 150,
          text: "• Auto Insurance\n• Home Insurance\n• Life Insurance\n• Business Insurance",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#f0f9ff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Insurance Types",
        },
        {
          id: "cta-1",
          type: "text",
          x: 50,
          y: 470,
          width: 800,
          height: 60,
          text: "Get a Free Quote: {{phone}}",
          fontSize: 32,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA",
        },
      ],
    },
  },
  {
    id: "dental-1",
    name: "Dental Practice",
    description: "Bright and clean dental office postcard",
    category: "dental",
    previewImage: "🦷",
    thumbnailUrl: dentalPreview,
    size: "4x6",
    industryVertical: "auto_service",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 400 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 400,
          fill: "#e0f2fe",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 40,
          y: 60,
          width: 520,
          height: 70,
          text: "Brighten Your Smile",
          fontSize: 42,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#0369a1",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "offer-1",
          type: "text",
          x: 60,
          y: 170,
          width: 480,
          height: 100,
          text: "New Patient Special\n$99 Cleaning, Exam & X-Rays",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#0c4a6e",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Offer",
        },
        {
          id: "cta-1",
          type: "text",
          x: 40,
          y: 310,
          width: 520,
          height: 50,
          text: "Call {{phone}} to Schedule",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#0369a1",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA",
        },
      ],
    },
  },
  {
    id: "moving-company-1",
    name: "Moving Company",
    description: "Professional moving services postcard",
    category: "moving",
    previewImage: "📦",
    thumbnailUrl: movingCompanyPreview,
    size: "6x9",
    industryVertical: "auto_service",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#0284c7",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 90,
          width: 800,
          height: 90,
          text: "Stress-Free Moving",
          fontSize: 56,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "services-1",
          type: "text",
          x: 100,
          y: 250,
          width: 700,
          height: 150,
          text: "✓ Local & Long Distance\n✓ Packing Services\n✓ Storage Solutions\n✓ Licensed & Insured",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#f0f9ff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Services",
        },
        {
          id: "cta-1",
          type: "text",
          x: 50,
          y: 470,
          width: 800,
          height: 60,
          text: "Free Quote: {{phone}}",
          fontSize: 34,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#f97316",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA",
        },
      ],
    },
  },
];

export const getTemplatesByCategory = (category: StarterTemplate["category"]) => {
  return starterTemplates.filter((template) => template.category === category);
};

export const getTemplateById = (id: string) => {
  return starterTemplates.find((template) => template.id === id);
};
