/**
 * InventoryAlertEmail Template
 * 
 * Email template for alerting admins about low gift card inventory
 */

import { renderEmailLayout } from './EmailLayout';

interface InventoryAlertEmailProps {
  alertLevel: 'warning' | 'critical' | 'empty';
  poolName: string;
  brandName: string;
  availableCards: number;
  totalCards: number;
  cardValue: number;
  poolId: string;
  dashboardUrl?: string;
}

export function InventoryAlertEmail({
  alertLevel,
  poolName,
  brandName,
  availableCards,
  totalCards,
  cardValue,
  poolId,
  dashboardUrl = 'https://app.mobul.com/gift-cards',
}: InventoryAlertEmailProps): string {
  const alertConfig = {
    warning: {
      icon: '⚠️',
      title: 'Low Inventory Warning',
      color: '#ffc107',
      bgColor: '#fff3cd',
      textColor: '#856404',
      message: 'Gift card inventory is running low and should be replenished soon.',
    },
    critical: {
      icon: '🚨',
      title: 'Critical Inventory Alert',
      color: '#dc3545',
      bgColor: '#f8d7da',
      textColor: '#721c24',
      message: 'Gift card inventory is critically low. Immediate attention required!',
    },
    empty: {
      icon: '❌',
      title: 'Inventory Depleted',
      color: '#dc3545',
      bgColor: '#f8d7da',
      textColor: '#721c24',
      message: 'Gift card pool is completely empty. Campaigns may be affected!',
    },
  };

  const config = alertConfig[alertLevel];
  const utilization = totalCards > 0 ? ((totalCards - availableCards) / totalCards * 100).toFixed(1) : '0';

  const emailBody = `
    <div class="card" style="background-color: ${config.bgColor}; border-left: 4px solid ${config.color};">
      <h2 style="color: ${config.textColor}; margin-top: 0; font-size: 24px;">
        ${config.icon} ${config.title}
      </h2>
      <p style="color: ${config.textColor}; font-size: 16px; margin-bottom: 0;">
        ${config.message}
      </p>
    </div>

    <div class="card">
      <h3 style="margin-top: 0; color: #333; font-size: 18px;">Pool Details</h3>
      <table style="width: 100%; border-collapse: collapse;">
        <tr>
          <td style="padding: 12px 0; color: #6c757d; border-bottom: 1px solid #e9ecef;">Pool Name:</td>
          <td style="padding: 12px 0; font-weight: 600; color: #333; border-bottom: 1px solid #e9ecef;">${poolName}</td>
        </tr>
        <tr>
          <td style="padding: 12px 0; color: #6c757d; border-bottom: 1px solid #e9ecef;">Brand:</td>
          <td style="padding: 12px 0; font-weight: 600; color: #333; border-bottom: 1px solid #e9ecef;">${brandName}</td>
        </tr>
        <tr>
          <td style="padding: 12px 0; color: #6c757d; border-bottom: 1px solid #e9ecef;">Card Value:</td>
          <td style="padding: 12px 0; font-weight: 600; color: #333; border-bottom: 1px solid #e9ecef;">$${cardValue}</td>
        </tr>
        <tr>
          <td style="padding: 12px 0; color: #6c757d; border-bottom: 1px solid #e9ecef;">Available Cards:</td>
          <td style="padding: 12px 0; font-weight: 600; color: ${availableCards === 0 ? '#dc3545' : '#ffc107'}; border-bottom: 1px solid #e9ecef;">
            ${availableCards} / ${totalCards}
          </td>
        </tr>
        <tr>
          <td style="padding: 12px 0; color: #6c757d;">Utilization:</td>
          <td style="padding: 12px 0; font-weight: 600; color: #333;">${utilization}%</td>
        </tr>
      </table>
    </div>

    <div class="card" style="background-color: #d1ecf1; border-left: 4px solid #0c5460;">
      <h3 style="margin-top: 0; color: #0c5460; font-size: 16px;">💡 Recommended Actions</h3>
      <ul style="color: #0c5460; margin: 0; padding-left: 20px;">
        ${availableCards === 0 ? `
          <li style="margin-bottom: 8px;">Purchase or upload new gift cards immediately</li>
          <li style="margin-bottom: 8px;">Pause campaigns using this pool to prevent failures</li>
          <li style="margin-bottom: 8px;">Notify call center team about inventory status</li>
        ` : `
          <li style="margin-bottom: 8px;">Purchase additional gift cards to maintain inventory</li>
          <li style="margin-bottom: 8px;">Review campaign usage and adjust quantities</li>
          <li style="margin-bottom: 8px;">Consider setting up auto-replenishment</li>
        `}
      </ul>
    </div>

    <p style="text-align: center; margin-top: 30px;">
      <a href="${dashboardUrl}/pools/${poolId}" class="button" style="background-color: ${config.color};">
        View Pool Details
      </a>
    </p>

    <p style="font-size: 14px; color: #6c757d; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e9ecef; text-align: center;">
      This alert was automatically generated by the Mobul platform.<br>
      Alert Level: <strong>${alertLevel.toUpperCase()}</strong> | Pool ID: ${poolId}
    </p>
  `;

  return renderEmailLayout({
    children: emailBody,
    preheader: `${config.title}: ${poolName} (${availableCards} cards remaining)`,
    clientName: 'Mobul Platform',
    logoUrl: undefined,
  });
}

export function renderInventoryAlertEmail(props: InventoryAlertEmailProps): string {
  return InventoryAlertEmail(props);
}

