import reiPostcardPreview from "@/assets/template-previews/rei-postcard.jpg";
import retailPromoPreview from "@/assets/template-previews/retail-promo.jpg";
import eventInvitePreview from "@/assets/template-previews/event-invite.jpg";
import roofingServicesPreview from "@/assets/template-previews/roofing-services.jpg";
import autoServicePreview from "@/assets/template-previews/auto-service.jpg";
import healthcareCheckupPreview from "@/assets/template-previews/healthcare-checkup.jpg";
import legalServicesPreview from "@/assets/template-previews/legal-services.jpg";
import realtorListingPreview from "@/assets/template-previews/realtor-listing.jpg";
import homeServicesPreview from "@/assets/template-previews/home-services.jpg";
import fitnessGymPreview from "@/assets/template-previews/fitness-gym.jpg";
import restaurantPromoPreview from "@/assets/template-previews/restaurant-promo.jpg";
import financialAdvisorPreview from "@/assets/template-previews/financial-advisor.jpg";
import landscapingPreview from "@/assets/template-previews/landscaping.jpg";
import veterinaryPreview from "@/assets/template-previews/veterinary.jpg";
import insurancePreview from "@/assets/template-previews/insurance.jpg";
import dentalPreview from "@/assets/template-previews/dental.jpg";
import movingCompanyPreview from "@/assets/template-previews/moving-company.jpg";

export interface StarterMailPiece {
  id: string;
  name: string;
  description: string;
  category: "real_estate" | "retail" | "event" | "roofing" | "auto" | "healthcare" | "legal" | "home_services" | "fitness" | "restaurant" | "financial" | "landscaping" | "veterinary" | "insurance" | "dental" | "moving";
  previewImage: string;
  thumbnailUrl: string;
  size: "4x6" | "6x9" | "6x11" | "letter" | "trifold";
  industryVertical: "roofing" | "rei" | "auto_service" | "auto_warranty" | "auto_buyback";
  layers: any;
}

export const starterMailPieces: StarterMailPiece[] = [
  {
    id: "rei-postcard-1",
    name: "Real Estate Investment Postcard",
    description: "Professional postcard for cash home buyers",
    category: "real_estate",
    previewImage: "🏠",
    thumbnailUrl: reiPostcardPreview,
    size: "6x9",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#1a365d",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 80,
          width: 800,
          height: 100,
          text: "We Buy Houses Fast For Cash",
          fontSize: 48,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 50,
          y: 200,
          width: 800,
          height: 60,
          text: "Any Condition • Any Situation • Fair Offers",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#f7fafc",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 300,
          y: 400,
          width: 300,
          height: 80,
          fill: "#e53e3e",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 300,
          y: 420,
          width: 300,
          height: 40,
          text: "Call Now: {{phone}}",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "retail-promo-1",
    name: "Retail Promotional Postcard",
    description: "Eye-catching postcard for retail promotions",
    category: "retail",
    previewImage: "🛍️",
    thumbnailUrl: retailPromoPreview,
    size: "4x6",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 900 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 900,
          fill: "#fbbf24",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 30,
          y: 50,
          width: 540,
          height: 80,
          text: "Big Sale This Weekend!",
          fontSize: 36,
          fontFamily: "Helvetica",
          fontWeight: "bold",
          fill: "#b45309",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 30,
          y: 150,
          width: 540,
          height: 60,
          text: "Up to 50% off on all items",
          fontSize: 24,
          fontFamily: "Helvetica",
          fontWeight: "normal",
          fill: "#78350f",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 250,
          width: 500,
          height: 400,
          src: retailPromoPreview,
          alt: "Retail Promo",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Promo Image",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 150,
          y: 700,
          width: 300,
          height: 80,
          fill: "#b45309",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 150,
          y: 720,
          width: 300,
          height: 40,
          text: "Shop Now",
          fontSize: 28,
          fontFamily: "Helvetica",
          fontWeight: "bold",
          fill: "#fbbf24",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "event-invite-1",
    name: "Event Invitation Postcard",
    description: "Elegant invitation for special events",
    category: "event",
    previewImage: "🎉",
    thumbnailUrl: eventInvitePreview,
    size: "6x11",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 1100, height: 1800 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 1100,
          height: 1800,
          fill: "#f3f4f6",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 100,
          y: 100,
          width: 900,
          height: 120,
          text: "You're Invited!",
          fontSize: 60,
          fontFamily: "Georgia",
          fontWeight: "bold",
          fill: "#1f2937",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "details-1",
          type: "text",
          x: 100,
          y: 250,
          width: 900,
          height: 200,
          text: "Join us for an evening of celebration on {{event_date}} at {{venue_name}}.",
          fontSize: 28,
          fontFamily: "Georgia",
          fontWeight: "normal",
          fill: "#4b5563",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Event Details",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 350,
          y: 1500,
          width: 400,
          height: 100,
          fill: "#2563eb",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "RSVP Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 350,
          y: 1520,
          width: 400,
          height: 60,
          text: "RSVP Now",
          fontSize: 36,
          fontFamily: "Georgia",
          fontWeight: "bold",
          fill: "#ffffff",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "RSVP Text",
        },
      ],
    },
  },
  {
    id: "roofing-services-1",
    name: "Roofing Services Postcard",
    description: "Professional postcard for roofing companies",
    category: "roofing",
    previewImage: "🏠",
    thumbnailUrl: roofingServicesPreview,
    size: "4x6",
    industryVertical: "roofing",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 900 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 900,
          fill: "#1e293b",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 30,
          y: 50,
          width: 540,
          height: 80,
          text: "Reliable Roofing Services",
          fontSize: 36,
          fontFamily: "Verdana",
          fontWeight: "bold",
          fill: "#fbbf24",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 30,
          y: 150,
          width: 540,
          height: 60,
          text: "Free estimates and 24/7 emergency service",
          fontSize: 24,
          fontFamily: "Verdana",
          fontWeight: "normal",
          fill: "#fbbf24",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 250,
          width: 500,
          height: 400,
          src: roofingServicesPreview,
          alt: "Roofing Services",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Roofing Image",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 150,
          y: 700,
          width: 300,
          height: 80,
          fill: "#fbbf24",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 150,
          y: 720,
          width: 300,
          height: 40,
          text: "Call Today: {{phone}}",
          fontSize: 28,
          fontFamily: "Verdana",
          fontWeight: "bold",
          fill: "#1e293b",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "auto-service-1",
    name: "Auto Service Postcard",
    description: "Postcard for auto repair and service shops",
    category: "auto",
    previewImage: "🚗",
    thumbnailUrl: autoServicePreview,
    size: "4x6",
    industryVertical: "auto_service",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 900 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 900,
          fill: "#111827",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 30,
          y: 50,
          width: 540,
          height: 80,
          text: "Trusted Auto Service",
          fontSize: 36,
          fontFamily: "Tahoma",
          fontWeight: "bold",
          fill: "#3b82f6",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 30,
          y: 150,
          width: 540,
          height: 60,
          text: "Quality repairs at affordable prices",
          fontSize: 24,
          fontFamily: "Tahoma",
          fontWeight: "normal",
          fill: "#93c5fd",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 250,
          width: 500,
          height: 400,
          src: autoServicePreview,
          alt: "Auto Service",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Auto Image",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 150,
          y: 700,
          width: 300,
          height: 80,
          fill: "#3b82f6",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 150,
          y: 720,
          width: 300,
          height: 40,
          text: "Book Your Appointment",
          fontSize: 28,
          fontFamily: "Tahoma",
          fontWeight: "bold",
          fill: "#111827",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "healthcare-checkup-1",
    name: "Healthcare Checkup Postcard",
    description: "Postcard for healthcare providers promoting checkups",
    category: "healthcare",
    previewImage: "🩺",
    thumbnailUrl: healthcareCheckupPreview,
    size: "4x6",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 900 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 900,
          fill: "#e0f2fe",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 30,
          y: 50,
          width: 540,
          height: 80,
          text: "Schedule Your Checkup Today",
          fontSize: 36,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#0369a1",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 30,
          y: 150,
          width: 540,
          height: 60,
          text: "Preventive care for a healthier life",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#0284c7",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 250,
          width: 500,
          height: 400,
          src: healthcareCheckupPreview,
          alt: "Healthcare Checkup",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Healthcare Image",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 150,
          y: 700,
          width: 300,
          height: 80,
          fill: "#0369a1",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 150,
          y: 720,
          width: 300,
          height: 40,
          text: "Call to Book",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#e0f2fe",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "legal-services-1",
    name: "Legal Services Postcard",
    description: "Postcard for law firms and legal services",
    category: "legal",
    previewImage: "⚖️",
    thumbnailUrl: legalServicesPreview,
    size: "4x6",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 900 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 900,
          fill: "#1f2937",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 30,
          y: 50,
          width: 540,
          height: 80,
          text: "Trusted Legal Advice",
          fontSize: 36,
          fontFamily: "Times New Roman",
          fontWeight: "bold",
          fill: "#f9fafb",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 30,
          y: 150,
          width: 540,
          height: 60,
          text: "Experienced attorneys ready to help",
          fontSize: 24,
          fontFamily: "Times New Roman",
          fontWeight: "normal",
          fill: "#d1d5db",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 250,
          width: 500,
          height: 400,
          src: legalServicesPreview,
          alt: "Legal Services",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Legal Image",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 150,
          y: 700,
          width: 300,
          height: 80,
          fill: "#374151",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 150,
          y: 720,
          width: 300,
          height: 40,
          text: "Contact Us",
          fontSize: 28,
          fontFamily: "Times New Roman",
          fontWeight: "bold",
          fill: "#f9fafb",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "realtor-listing-1",
    name: "Realtor Listing Postcard",
    description: "Postcard for real estate listings",
    category: "real_estate",
    previewImage: "🏡",
    thumbnailUrl: realtorListingPreview,
    size: "6x9",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 900, height: 600 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: "#f9fafb",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 50,
          y: 50,
          width: 800,
          height: 100,
          text: "Beautiful Family Home For Sale",
          fontSize: 48,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#111827",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 180,
          width: 800,
          height: 350,
          src: realtorListingPreview,
          alt: "Realtor Listing",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Listing Image",
        },
        {
          id: "price-1",
          type: "text",
          x: 50,
          y: 550,
          width: 800,
          height: 50,
          text: "Price: $450,000",
          fontSize: 32,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#2563eb",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Price",
        },
      ],
    },
  },
  {
    id: "home-services-1",
    name: "Home Services Postcard",
    description: "Postcard for home repair and maintenance services",
    category: "home_services",
    previewImage: "🔧",
    thumbnailUrl: homeServicesPreview,
    size: "4x6",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 900 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 900,
          fill: "#f3f4f6",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 30,
          y: 50,
          width: 540,
          height: 80,
          text: "Trusted Home Services",
          fontSize: 36,
          fontFamily: "Verdana",
          fontWeight: "bold",
          fill: "#111827",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 30,
          y: 150,
          width: 540,
          height: 60,
          text: "Repairs, maintenance, and more",
          fontSize: 24,
          fontFamily: "Verdana",
          fontWeight: "normal",
          fill: "#374151",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 250,
          width: 500,
          height: 400,
          src: homeServicesPreview,
          alt: "Home Services",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Home Services Image",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 150,
          y: 700,
          width: 300,
          height: 80,
          fill: "#2563eb",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 150,
          y: 720,
          width: 300,
          height: 40,
          text: "Call for a Quote",
          fontSize: 28,
          fontFamily: "Verdana",
          fontWeight: "bold",
          fill: "#f3f4f6",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "fitness-gym-1",
    name: "Fitness Gym Postcard",
    description: "Postcard for gym promotions and memberships",
    category: "fitness",
    previewImage: "🏋️‍♂️",
    thumbnailUrl: fitnessGymPreview,
    size: "4x6",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 900 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 900,
          fill: "#111827",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 30,
          y: 50,
          width: 540,
          height: 80,
          text: "Get Fit Today!",
          fontSize: 36,
          fontFamily: "Impact",
          fontWeight: "bold",
          fill: "#fbbf24",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 30,
          y: 150,
          width: 540,
          height: 60,
          text: "Join our gym and save 20%",
          fontSize: 24,
          fontFamily: "Impact",
          fontWeight: "normal",
          fill: "#fbbf24",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 250,
          width: 500,
          height: 400,
          src: fitnessGymPreview,
          alt: "Fitness Gym",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Gym Image",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 150,
          y: 700,
          width: 300,
          height: 80,
          fill: "#fbbf24",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 150,
          y: 720,
          width: 300,
          height: 40,
          text: "Sign Up Now",
          fontSize: 28,
          fontFamily: "Impact",
          fontWeight: "bold",
          fill: "#111827",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "restaurant-promo-1",
    name: "Restaurant Promotional Postcard",
    description: "Postcard for restaurant specials and events",
    category: "restaurant",
    previewImage: "🍽️",
    thumbnailUrl: restaurantPromoPreview,
    size: "4x6",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 900 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 900,
          fill: "#7c2d12",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 30,
          y: 50,
          width: 540,
          height: 80,
          text: "Delicious Meals Await",
          fontSize: 36,
          fontFamily: "Georgia",
          fontWeight: "bold",
          fill: "#fbbf24",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 30,
          y: 150,
          width: 540,
          height: 60,
          text: "Join us for happy hour specials",
          fontSize: 24,
          fontFamily: "Georgia",
          fontWeight: "normal",
          fill: "#fde68a",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 250,
          width: 500,
          height: 400,
          src: restaurantPromoPreview,
          alt: "Restaurant Promo",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Restaurant Image",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 150,
          y: 700,
          width: 300,
          height: 80,
          fill: "#b45309",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 150,
          y: 720,
          width: 300,
          height: 40,
          text: "Reserve Your Table",
          fontSize: 28,
          fontFamily: "Georgia",
          fontWeight: "bold",
          fill: "#fef3c7",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "financial-advisor-1",
    name: "Financial Advisor Postcard",
    description: "Postcard for financial advisors and planners",
    category: "financial",
    previewImage: "💼",
    thumbnailUrl: financialAdvisorPreview,
    size: "4x6",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 900 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 900,
          fill: "#1e293b",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 30,
          y: 50,
          width: 540,
          height: 80,
          text: "Plan Your Financial Future",
          fontSize: 36,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#fbbf24",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 30,
          y: 150,
          width: 540,
          height: 60,
          text: "Expert advice for your investments",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#fde68a",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 250,
          width: 500,
          height: 400,
          src: financialAdvisorPreview,
          alt: "Financial Advisor",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Financial Image",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 150,
          y: 700,
          width: 300,
          height: 80,
          fill: "#b45309",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 150,
          y: 720,
          width: 300,
          height: 40,
          text: "Schedule a Consultation",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#fef3c7",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "landscaping-1",
    name: "Landscaping Services Postcard",
    description: "Postcard for landscaping and lawn care",
    category: "landscaping",
    previewImage: "🌿",
    thumbnailUrl: landscapingPreview,
    size: "4x6",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 900 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 900,
          fill: "#065f46",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 30,
          y: 50,
          width: 540,
          height: 80,
          text: "Beautiful Landscaping Services",
          fontSize: 36,
          fontFamily: "Georgia",
          fontWeight: "bold",
          fill: "#a7f3d0",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 30,
          y: 150,
          width: 540,
          height: 60,
          text: "Transform your yard today",
          fontSize: 24,
          fontFamily: "Georgia",
          fontWeight: "normal",
          fill: "#6ee7b7",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 250,
          width: 500,
          height: 400,
          src: landscapingPreview,
          alt: "Landscaping",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Landscaping Image",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 150,
          y: 700,
          width: 300,
          height: 80,
          fill: "#10b981",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 150,
          y: 720,
          width: 300,
          height: 40,
          text: "Get a Free Quote",
          fontSize: 28,
          fontFamily: "Georgia",
          fontWeight: "bold",
          fill: "#d1fae5",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "veterinary-1",
    name: "Veterinary Services Postcard",
    description: "Postcard for veterinary clinics and pet care",
    category: "veterinary",
    previewImage: "🐾",
    thumbnailUrl: veterinaryPreview,
    size: "4x6",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 900 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 900,
          fill: "#fef3c7",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 30,
          y: 50,
          width: 540,
          height: 80,
          text: "Caring Veterinary Services",
          fontSize: 36,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#78350f",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 30,
          y: 150,
          width: 540,
          height: 60,
          text: "Compassionate care for your pets",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#92400e",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 250,
          width: 500,
          height: 400,
          src: veterinaryPreview,
          alt: "Veterinary Services",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Veterinary Image",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 150,
          y: 700,
          width: 300,
          height: 80,
          fill: "#78350f",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 150,
          y: 720,
          width: 300,
          height: 40,
          text: "Book an Appointment",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#fef3c7",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "insurance-1",
    name: "Insurance Services Postcard",
    description: "Postcard for insurance agents and brokers",
    category: "insurance",
    previewImage: "🛡️",
    thumbnailUrl: insurancePreview,
    size: "4x6",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 900 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 900,
          fill: "#1e40af",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 30,
          y: 50,
          width: 540,
          height: 80,
          text: "Protect What Matters",
          fontSize: 36,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#bfdbfe",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 30,
          y: 150,
          width: 540,
          height: 60,
          text: "Affordable insurance plans for you",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#93c5fd",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 250,
          width: 500,
          height: 400,
          src: insurancePreview,
          alt: "Insurance Services",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Insurance Image",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 150,
          y: 700,
          width: 300,
          height: 80,
          fill: "#3b82f6",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 150,
          y: 720,
          width: 300,
          height: 40,
          text: "Get a Quote",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#bfdbfe",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "dental-1",
    name: "Dental Services Postcard",
    description: "Postcard for dental clinics and dentists",
    category: "dental",
    previewImage: "🦷",
    thumbnailUrl: dentalPreview,
    size: "4x6",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 900 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 900,
          fill: "#fef3c7",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 30,
          y: 50,
          width: 540,
          height: 80,
          text: "Brighten Your Smile",
          fontSize: 36,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#78350f",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 30,
          y: 150,
          width: 540,
          height: 60,
          text: "Comprehensive dental care for all ages",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#92400e",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 250,
          width: 500,
          height: 400,
          src: dentalPreview,
          alt: "Dental Services",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Dental Image",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 150,
          y: 700,
          width: 300,
          height: 80,
          fill: "#78350f",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 150,
          y: 720,
          width: 300,
          height: 40,
          text: "Book Your Appointment",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#fef3c7",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
  {
    id: "moving-company-1",
    name: "Moving Company Postcard",
    description: "Postcard for moving and relocation services",
    category: "moving",
    previewImage: "🚚",
    thumbnailUrl: movingCompanyPreview,
    size: "4x6",
    industryVertical: "rei",
    layers: {
      version: 1,
      canvasSize: { width: 600, height: 900 },
      layers: [
        {
          id: "bg-1",
          type: "rect",
          x: 0,
          y: 0,
          width: 600,
          height: 900,
          fill: "#1e40af",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Background",
        },
        {
          id: "header-1",
          type: "text",
          x: 30,
          y: 50,
          width: 540,
          height: 80,
          text: "Stress-Free Moving Services",
          fontSize: 36,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#bfdbfe",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Headline",
        },
        {
          id: "subheader-1",
          type: "text",
          x: 30,
          y: 150,
          width: 540,
          height: 60,
          text: "Reliable and affordable movers",
          fontSize: 24,
          fontFamily: "Arial",
          fontWeight: "normal",
          fill: "#93c5fd",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Subheadline",
        },
        {
          id: "image-1",
          type: "image",
          x: 50,
          y: 250,
          width: 500,
          height: 400,
          src: movingCompanyPreview,
          alt: "Moving Company",
          fit: "cover",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "Moving Image",
        },
        {
          id: "cta-1",
          type: "rect",
          x: 150,
          y: 700,
          width: 300,
          height: 80,
          fill: "#3b82f6",
          stroke: "",
          strokeWidth: 0,
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Button",
        },
        {
          id: "cta-text-1",
          type: "text",
          x: 150,
          y: 720,
          width: 300,
          height: 40,
          text: "Get a Free Estimate",
          fontSize: 28,
          fontFamily: "Arial",
          fontWeight: "bold",
          fill: "#bfdbfe",
          align: "center",
          opacity: 1,
          rotation: 0,
          locked: false,
          visible: true,
          name: "CTA Text",
        },
      ],
    },
  },
];
